#Compose for postgres database
version: '3.1'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
  chess-backend:
    image: m0ttii/chess-backend:latest
    restart: always
    platform: linux/amd64
    ports:
      - "8080:8080"

networks:
    default:
        name: chess-network

volumes:
    redis:
      driver: local
